package com.thillai.martialarts.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "students")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Student {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Public-facing code, e.g. TMA0001 — generated by StudentService */
    @Column(nullable = false, unique = true, length = 20)
    private String studentId;

    @Column(nullable = false, length = 120)
    private String name;

    private Integer age;

    private LocalDate dob;

    @Column(nullable = false, unique = true, length = 15)
    private String mobile;

    @Column(length = 255)
    private String photoUrl;

    @Column(length = 255)
    private String aadhaarPdfUrl;

    private LocalDate joiningDate;

    @Column(length = 500)
    private String reasonForJoining;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "batch_id")
    private Batch batch;

    @ManyToMany
    @JoinTable(
        name = "student_courses",
        joinColumns = @JoinColumn(name = "student_id"),
        inverseJoinColumns = @JoinColumn(name = "course_id")
    )
    @Builder.Default
    private List<Course> courses = new ArrayList<>();

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id")
    private User user;

    @Column(nullable = false)
    @Builder.Default
    private Integer monthlyFee = 0;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    void onCreate() {
        this.createdAt = LocalDateTime.now();
    }
}
